### ISSUE TITLE
Ошибка

### ISSUE THREAD

**Issue by andreymarrr** [VSBoiko/invers_tic_tac_toe_10x10#1]
https://github.com/VSBoiko/invers_tic_tac_toe_10x10/blob/abb1e35dfc7a40d9a0147f0c610ed49b9d58ac74/index.py#L58

Ошибка в выводе победного знака. В принте вместо self.game_result нужно поставить self.current_player_mark .

**Comment by VSBoiko** [comment]
Принял, спасибо!24.01.2022, 22:15, "andrasmarko" ***@***.***>:
https://github.com/VSBoiko/invers_tic_tac_toe_10x10/blob/abb1e35dfc7a40d9a0147f0c610ed49b9d58ac74/index.py#L58
Ошибка в выводе победного знака. В принте вместо self.game_result нужно поставить self.current_player_mark .
